### ISSUE TITLE
Allow easily plugging 'modular' code into a project

### ISSUE THREAD

**Issue by moonheart08** [ponylang/rfcs#110]
Essentially, add a compiletime way of modularly adding code to the program.
Say we have the following program:
> main.pony
> src/
>    foo-module
>    bar-module
>    importthemodules.pony
>    dothings.pony

'importthemodules.pony' serves one purpose in this example: 'use' all the modules, and run their init function on a class, we'll call this class 'baz'

It could, with my idea, _potentially_ be structured to look like this:
> main.pony
> src/
>     modules/
>          foo
>          bar
>     dothings.pony

What's happening here? Well, in main.pony, we simply are 'use' ing all the modules at once, and setting each one up in a modular fashion, without even explictly mentioning the modules (just giving them their own folder)

This is just a simple concept, completely unpolished, please consider it. But remember absolutely none of this is a final idea, its a unpolished, probably dangerous concept.

**Comment by moonheart08** [comment]
Ok, i seriously need to read the issue list more. 'hot code loading' already approaches this idea.
Closing.

**Comment by SeanTAllen** [comment]
@moonheart08 i dont see how this is the same as hot code loading. perhaps i misunderstood. hot code loading isn't compile time.

**Comment by jemc** [comment]
@moonheart08 - I don't think I fully understand what you're proposing.

Can you provide a less abstract example that shows a real use case where this is desirable, and explain what is happening in the proposed behaviour?

**Comment by moonheart08** [comment]
...Thats what i get for filing a issue on little sleep!
I'll update the issue with a clear explanation soon. This could take some time.

**Comment by moonheart08** [comment]
In fact, i'll do it in a new issue.
Now, back to being disorganized. (Will file soon)
