### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by moonheart08** [ponylang/rfcs#111]
_This is a concept, not a final draft, it will almost definitely break everything if you try and implement it.
In fact, don't try at all, it probably wont even work._
A Module is a version of a Package that 'plugs in' to it's parent code, and the parent does not know types from the child (But could be depended upon by other modules in the code, which CAN access another module's types)
a Module only has to provide one actor, its own Main, which provides create(). 
the program that is the module's parent is given a list of some sort that contains all the Module actors. These actors will, in your average use case, probably implement multiple different Traits and Interfaces.
Modules can pass around their own internal structs, even if the main program doesn't actually recognize them, because they are found and noted at compile time, where this can be done easily and efficiently, and can be treated as one large program.

**Comment by jemc** [comment]
I'm having trouble reconciling these two statements in my understanding, as they seem at first glance to be contradictory to me:

> is not referenced directly by the parent

> parent is given a list of some sort that contains all the Module actors

**Comment by moonheart08** [comment]
You're right that is a little contradictory. I'll fix that.
The intention was the parent doesn't have to know types from the child, and could just reference the child's types via traits they implement.

**Comment by Praetonus** [comment]
I don't really see the benefits of having a language and/or compiler concept for that. You can already do that with private types hidden behind public traits.

Do you have a use case in mind that isn't covered by private types?

**Comment by moonheart08** [comment]
Extending large programs modularly, without having to dig into the main program, just add modules.

**Comment by jemc** [comment]
@moonheart08 - maybe you could provide an example of something you wanted to do, and found that the current features of the language didn't get you there?

Then we could either help to refine your idea or show the current features that provide the features you need.

**Comment by moonheart08** [comment]
I'm working on a modular, simple 'game'. 
What i wanted to do was to make it extremely easy to extend, by having the engine be the main program, and have all the content in individual modules. Of course, I quickly found that i'd have to do extra work that could potentially add up very quickly (File that 'use's all the modules, creates the module's actor, and then runs preinit, init, and postinit functions from each module)
Imagine having 100~ modules in one program. 100 lines of uses would be rather annoying to maintain.

**Comment by jemc** [comment]
I don't know that what you're describing would map very cleanly to a general language feature, but maybe if you shared more detail about how you'd expect it to look, I could comment further.

It's worth noting that we have a situation similar to what you describe in https://github.com/ponylang/ponyc/blob/master/packages/stdlib/_test.pony

If maintaining something like that is too onerous, my first thought would be to script it as a code generation step in your project's `Makefile`.

**Comment by codec-abc** [comment]
@moonheart08 Can't you put all your modules into a single package (but in different files to keep it clean) so you can have a single use line?

**Comment by moonheart08** [comment]
...damnit. why the didn't i think of that. Excellent point. Only issue now is the lack of easy initalization without boilerplate

**Comment by codec-abc** [comment]
It depends if you have dependencies (even implicit ones) between your modules. If you cannot initialize all your modules in any random order then you need to tell in which order the modules should be initialized and thus the boilerplate become necessary. In my experience, it is rather rare to have all modules of a game completely independent (either directly or indirectly) from each other.

**Comment by moonheart08** [comment]
True. Of course, modules have `new create()` as well, so during compile time, all creation calls for modules could be appropriately organized.

**Comment by zzz6519003** [comment]
could you do a nicer title?

**Comment by SeanTAllen** [comment]
Seems like @moonheart08 gave up on this idea. Closing for now.

**Comment by moonheart08** [comment]
I forgot this even existed. Plus my game moved over to Rust.
Indeed I did.
