### ISSUE TITLE
Create RFC for collection initializers

### ISSUE THREAD

**Issue by SCKelemen** [ponylang/rfcs#132]
I'm creating an Issue based on the comments in #131 to remind myself to draft an RFC for static collection initializers.
```pony
let collection = { 0, 2, 4, 8 }
```

**Comment by Theodus** [comment]
I'm not sure that this can be done with the `{` and `}` delimiters if we intend to keep the Pony grammar LL(1). I would be interested to see an RFC on this issue, however it may be necessary to change the syntax so that is doesn't conflict with lambdas.

**Comment by SCKelemen** [comment]
I was thinking about how to declare the type of the collection anyway. Perhaps this makes more sense:
```pony
let collection = int[]{ 1, 2, 3, 4 }
```

another concern is simple arrays; for those, perhaps using the bracket makes more sense:
```pony
let array = [ 1, 2, 3, 4]
```
and last, how to instantiate complex types like hashmaps:
```pony
let map = {
                   { "KEY", "VALUE" },
                   { "KEY2", "VALUE" },
                 }
```

So including the type, it might look like this:
```pony
let map = hashmap<string,string>{
                   { "KEY", "VALUE" },
                   { "KEY2", "VALUE" },
                 }
```
syntax for illustration purposes only, as it doesn't follow the pony syntax
