### ISSUE TITLE
"not match" and "not if"

### ISSUE THREAD

**Issue by adri326** [ponylang/rfcs#140]
# "not match" and "not if"

*This is a repost of the issue mentionned in #139*

Doing `not match ... end` and `not if ... end` [results in an error](https://playground.ponylang.io/?gist=2652feb86d95f77db66c4b1589358beb):

```
syntax error: expected expression after not
```

As the documentation states, `if ... end` and `match ... end` are expressions, so this edge case should not return this particular error.
This issue is only minor, as putting parentheses around the `match` or the `if` expression fixes the issue.

**Comment by SeanTAllen** [comment]
I'm sorry, why is this an RFC issue? if you believe its a bug, then it should be opened on ponyc.

Perhaps I'm not understanding. Well, almost assuredly I'm not. Can you explain?

**Comment by adri326** [comment]
My mistake, I believed it should be posted here, let me move this on ponyc
