### ISSUE TITLE
Expand or extract logging package from stdlib

### ISSUE THREAD

**Issue by jasoncarr0** [ponylang/rfcs#181]
The baseline logging in Pony is incredibly simple, but leans perhaps too much so. In order to support RFCs like RFC 67 (#175), we may need to expand the interface to be more flexible in passing information, besides the simple string computations of the current logger design.

Pony's standard library is not meant to be "batteries-included", in implementing all features. Nevertheless, a standard interface for logging will allow more code to interact in the future, and ensure critically important consistency in output. There are many existing, mature logging facades in other languages, which we may use for reference. Some such mature facades include [SLF4J](https://en.wikipedia.org/wiki/SLF4J), [python's logging module](https://docs.python.org/3/library/logging.html), as well as competing standards such as [Flogger](https://github.com/google/flogger)

**Comment by SeanTAllen** [comment]
I think it should be removed from the standard library and moved into its own ponylang/logger or similar package.

**Comment by jasoncarr0** [comment]
Agreed, if it's not needed inside the standard library (and I can't think of a reason it would be: errors should have a single meaning, and the standard library won't have any context about the user's program).

**Comment by SeanTAllen** [comment]
At sync @jemc said he wasn't opposed to the removal.
