### ISSUE TITLE
Incorrect division by 0 (1 / 0 -> ∞, in Pony 1 / 0 == 0)

### ISSUE THREAD

**Issue by igotfr** [ponylang/rfcs#189]
operation | Pony | Math
------------ | ------- | -------
x / 0 | 0 | ∞

## Arithmetic operations between real numbers and infinity

operation | Pony | Math
------------ | ------- | -------
x + ∞ | I don't know | ∞
x - ∞ | I don't know | -∞
x / ∞ | I don't know | 0
x / -∞ | I don't know | 0
x > 0 => x * ∞ | I don't know | ∞
x > 0 => x * -∞ | I don't know | -∞
x < 0 => x * ∞ | I don't know | -∞
x < 0 => x * -∞ | I don't know | ∞

## Arithmetic operations between infinities

operation | Pony | Math
------------ | ------- | -------
∞ + ∞ | I don't know | ∞
-∞ - ∞ | I don't know | -∞
∞ * ∞ | I don't know | ∞
-∞ * -∞ | I don't know | ∞

## Undefineds
0 * ∞

0 * -∞

∞ - ∞

±∞ / ±∞

(±∞) ^ 0

1 ^ ±∞

**Comment by SeanTAllen** [comment]
This is intentional. I'm closing this issue. It's not incorrect. I'm not allowing another flamewar to start around this so I'm going to lock the issue.

https://tutorial.ponylang.io/gotchas/divide-by-zero.html
