### ISSUE TITLE
Allow pointers to functions as members of Struct

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/rfcs#54]
This request to create a RFC comes from [issue 440](https://github.com/ponylang/ponyc/issues/440) on the ponyc repo.

Currently some APIs are unusable via FFI because they require a pointer to a function to use as a callback. Full details are in the original issue and should be addressed in the RFC.

**Comment by Praetonus** [comment]
This is supported since the addition of bare lambdas.
