### ISSUE TITLE
Exhaustive match and unreachable cases

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/rfcs#56]
This was originally opened as ponyc [issue 60](https://github.com/ponylang/ponyc/issues/60).

> If we can prove a match is exhaustive, we can give an error if an else branch is present, and we can avoid unioning None with the expression type (from an else branch that will never be taken).
> If we can prove that a match case is unreachable, we can give an error.

Specifically:

> As previously discussed, since values are matched by calling eq(), we absolutely cannot determine if a set of matches are exhaustive if values are matched and any types involved provide their own eq().
> However, we can do checks when matching is based only on type. I think this would be well worth doing to aid cases such as switching on an enum.

See original issue for full details.

**Comment by jemc** [comment]
I started taking a look at this. I have a general plan about how to approach solving exhaustive match for the basic cases.  Will give it a try in my fork of the compiler, and write up an RFC if it goes well.

Honestly this change could probably bypass RFC via principle of least surprise, but at least having an RFC will give better visibility to the change and the thinking behind its implementation.

**Comment by SeanTAllen** [comment]
Agreed @jemc on all counts.

**Comment by jemc** [comment]
Implemented this last night, in this commit: https://github.com/ponylang/ponyc/commit/c697e8b

The commit depends on https://github.com/ponylang/ponyc/pull/1715 getting merged, since the work was done on top of that branch.

Will write up the RFC soon.
