### ISSUE TITLE
Type language for changing generated code based on type parameter constraints.

### ISSUE THREAD

**Issue by jemc** [ponylang/rfcs#60]
We're looking someone to make a proposal for a type language for changing generated code based on type parameter constraints, based on discussion here: https://github.com/ponylang/ponyc/issues/683

**Comment by Praetonus** [comment]
I'll write up something on that one.

**Comment by Praetonus** [comment]
Done. See #62.

**Comment by jemc** [comment]
Thanks @Praetonus!  I'm going to close this ticket, since the RFC now exists as a PR and future discussion can be directed there.
